'use strict'

const test = require('node:test')
const assert = require('node:assert')
const path = require('node:path')

const {
  parseBreakdown,
  packageForFile,
  aggregateByPackage,
  totalStats,
  coverageRatio,
  diffStats,
  totalRatioDiff,
} = require('../src/breakdown.js')

const FIXTURES = path.join(__dirname, 'fixtures')

test('parseBreakdown reads semicolon-delimited path;total;covered lines', () => {
  const stats = parseBreakdown('a/b.go;10;7\na/c.go;3;3\n')
  assert.deepStrictEqual(stats, [
    { name: 'a/b.go', total: 10, covered: 7 },
    { name: 'a/c.go', total: 3, covered: 3 },
  ])
})

test('parseBreakdown ignores blank lines and trims whitespace', () => {
  const stats = parseBreakdown('\n  a/b.go;10;7  \n\n')
  assert.deepStrictEqual(stats, [{ name: 'a/b.go', total: 10, covered: 7 }])
})

test('parseBreakdown rejects a line that is not three fields', () => {
  assert.throws(() => parseBreakdown('a/b.go;10\n'), /malformed breakdown line/i)
})

test('parseBreakdown rejects non-numeric counts', () => {
  assert.throws(() => parseBreakdown('a/b.go;ten;7\n'), /malformed breakdown line/i)
})

test('packageForFile takes everything before the last slash, with no rollup', () => {
  assert.strictEqual(packageForFile('internal/tariff/courier/client.go'), 'internal/tariff/courier')
  assert.strictEqual(packageForFile('main.go'), 'main.go')
})

test('aggregateByPackage keeps a parent package separate from its children', () => {
  const pkgs = aggregateByPackage([
    { name: 'internal/tariff/a.go', total: 100, covered: 50 },
    { name: 'internal/tariff/b.go', total: 44, covered: 44 },
    { name: 'internal/tariff/courier/c.go', total: 10, covered: 0 },
  ])
  assert.deepStrictEqual(pkgs, [
    { name: 'internal/tariff', total: 144, covered: 94 },
    { name: 'internal/tariff/courier', total: 10, covered: 0 },
  ])
})

test('coverageRatio returns exactly 100 when fully covered and 0 for an empty package', () => {
  assert.strictEqual(coverageRatio(0, 0), 0)
  assert.strictEqual(coverageRatio(3, 3), 100)
  assert.strictEqual(coverageRatio(8, 2), 25)
})

// Cross-check against the sample profile shipped in this repo. cover.out was produced
// with -coverpkg=./..., so its blocks repeat 14-15 times; the fixture breakdown file was
// generated by collapsing duplicate blocks (ADR-0001) exactly as go-test-coverage does.
test('the sample fixture totals 989 statements at 76.8% across 18 packages', () => {
  const fs = require('node:fs')
  const stats = parseBreakdown(fs.readFileSync(path.join(FIXTURES, 'sample-breakdown.txt'), 'utf8'))
  const pkgs = aggregateByPackage(stats)
  const total = totalStats(stats)

  assert.strictEqual(stats.length, 35)
  assert.strictEqual(pkgs.length, 18)
  assert.strictEqual(total.total, 989)
  assert.strictEqual(coverageRatio(total.total, total.covered).toFixed(1), '76.8')
})

test('diffStats reports a package whose uncovered count moved', () => {
  const current = [{ name: 'p', total: 10, covered: 6 }]
  const base = [{ name: 'p', total: 10, covered: 4 }]
  assert.deepStrictEqual(diffStats(current, base), [{ current: current[0], base: base[0] }])
})

test('diffStats reports a package absent from the baseline as new', () => {
  const current = [{ name: 'p', total: 10, covered: 6 }]
  assert.deepStrictEqual(diffStats(current, []), [{ current: current[0], base: null }])
})

// Replicated upstream quirk, see go-test-coverage calculateStatsDiff.
test('diffStats omits a package that is now fully covered', () => {
  const current = [{ name: 'p', total: 10, covered: 10 }]
  const base = [{ name: 'p', total: 10, covered: 4 }]
  assert.deepStrictEqual(diffStats(current, base), [])
})

test('diffStats omits a package whose uncovered count is unchanged', () => {
  const current = [{ name: 'p', total: 10, covered: 6 }]
  const base = [{ name: 'p', total: 10, covered: 6 }]
  assert.deepStrictEqual(diffStats(current, base), [])
})

test('totalRatioDiff is the current total ratio minus the base, to two decimals', () => {
  const current = [{ name: 'p', total: 3, covered: 2 }]
  const base = [{ name: 'p', total: 3, covered: 1 }]
  assert.strictEqual(totalRatioDiff(current, base), 33.33)
})
